---

- name: Gathering facts from all the servers
  hosts: all

- name: configure and deploy the webservers and application code
  hosts: webservers
  roles:
    - web

- name: deploy MySQL and configure the databases
  hosts: dbservers
  roles:
    - db
