---

- name: Gathering facts from all the servers
  hosts: all

- name: configure and deploy the webservers and application code
  hosts: webservers
  tasks:
  - name: Install httpd and php
    yum: name={{ item }} state=present
    with_items:
    - httpd
    - php
    - php-mysqlnd
    - git

  - name: Start firewalld
    service: name=firewalld state=started enabled=yes

  - name: insert firewalld rule for httpd
    firewalld: port=3306/tcp permanent=true state=enabled immediate=yes

  - name: http service state
    service: name=httpd state=started enabled=yes

  - name: Configure SELinux to allow httpd to connect to remote database
    seboolean: name=httpd_can_network_connect_db state=true persistent=yes
  
  - name: Copy the code from repository
    git: repo=https://github.com/bennojoy/mywebapp.git dest=/var/www/html/
  
  - name: Creates the index.php file
    template: src=index.php.j2 dest=/var/www/html/index.php


- name: deploy MySQL and configure the databases
  hosts: dbservers
  tasks:
  - name: Install MariaDB package
    yum: name={{ item }} state=installed
    with_items:
     - mariadb-server
     - python3-PyMySQL
  
  - name: Configure SELinux to start mysql on any port
    seboolean: name=mysql_connect_any state=true persistent=yes
  
  - name: Start MariaDB Service
    service: name=mariadb state=started enabled=yes
  
  - name: Start firewalld
    service: name=firewalld state=started enabled=yes
  
  - name: insert firewalld rule
    firewalld: port=3306/tcp permanent=true state=enabled immediate=yes
  
  - name: Create Application Database
    mysql_db: 
      name: "{{ item }}"
      login_unix_socket: /var/lib/mysql/mysql.sock
      state: present
    with_items: 
      - dishwashers
      - washing_machines
      - refregirators
    
  - name: Create Application DB User
    mysql_user: name=foouser password=abc priv=*.*:ALL host='%' login_unix_socket=/var/lib/mysql/mysql.sock state=present
    
